import { Language, Platform, Activity } from './types';

// Telegram Channel Link (Mock)
export const TELEGRAM_LINK = "https://t.me/betbounty_official";

export const LANGUAGES: Record<Language, { label: string; flag: string; currency: string; rate: number }> = {
  en: { label: 'English', flag: '🇺🇸', currency: '$', rate: 1 }, 
  zh: { label: '中文', flag: '🇨🇳', currency: '¥', rate: 1 },
  id: { label: 'Indonesia', flag: '🇮🇩', currency: 'Rp', rate: 1 },
  th: { label: 'ไทย', flag: '🇹🇭', currency: '฿', rate: 1 },
  vi: { label: 'Tiếng Việt', flag: '🇻🇳', currency: '₫', rate: 1 },
  ms: { label: 'Melayu', flag: '🇲🇾', currency: 'RM', rate: 1 },
  tl: { label: 'Pilipino', flag: '🇵🇭', currency: '₱', rate: 1 },
};

export const TRANSLATIONS = {
  en: {
    home: 'Home',
    earn: 'Earn',
    tasks: 'Tasks',
    profile: 'Me',
    referral: 'Invite',
    login: 'Login',
    register: 'Register',
    merchantLogin: 'Merchant Portal',
    phone: 'Phone Number',
    password: 'Password',
    verifyCode: 'SMS Code',
    getCode: 'Get Code',
    appName: 'BetBounty',
    balance: 'Balance',
    withdraw: 'Withdraw',
    bindCard: 'Bind Card',
    totalEarnings: 'Total Earnings',
    submitProof: 'Submit Proof',
    uploadScreenshot: 'Upload Screenshot',
    audit: 'Audit',
    approve: 'Approve',
    reject: 'Reject',
    status: { ongoing: 'To Do', reviewing: 'Reviewing', completed: 'Completed', rejected: 'Rejected' },
    adminTabs: { users: 'Users', tasks: 'Tasks', activities: 'Activities', audit: 'Task Audit' },
    sort: 'Sort',
    sortNew: 'Newest',
    sortReward: 'Reward',
    sortDeposit: 'Deposit',
    startTask: 'Join Now',
    steps: 'Steps',
    rules: 'Rules',
    uploadPlatform: 'Publish Task',
    hot: 'HOT',
    reward: 'Reward',
    remaining: 'Left',
    activityTitle: 'Special Event',
    play: 'Go Now',
    wait: 'Wait',
    sent: 'Sent',
    submit: 'Submit',
    myTasksTitle: 'My Tasks',
    noTasks: 'No tasks found',
    scanQr: 'Scan to Join',
    shareCode: 'My Referral Code',
    shareLink: 'Share Link',
    copy: 'Copy',
    copied: 'Copied!',
    messages: 'Messages',
    notifications: 'Notifications',
    telegram: 'Channel',
    referralRules: 'Invite & Earn Forever',
    referralDesc: 'Invite friends to join and earn commissions on every task they complete. Build your team!',
    level1: 'Level 1 (Direct)',
    level2: 'Level 2',
    level3: 'Level 3',
    bankName: 'Bank Name',
    accHolder: 'Account Holder',
    accNumber: 'Account Number',
    save: 'Save',
    cancel: 'Cancel',
    activityName: 'Activity Title',
    targetCountry: 'Target Country',
    uploadImage: 'Upload Image',
    addActivity: 'Add Activity',
    activityContent: 'Activity Content',
    createTask: 'Create New Task',
    taskName: 'Task Name',
    taskDesc: 'Description',
    taskRules: 'Rules',
    taskReward: 'Reward Amount',
    example: 'Example',
    refExampleA: 'You (A)',
    refExampleB: 'Friend (B)',
    refExampleC: 'Friend (C)',
    refExampleD: 'Friend (D)',
    refCalc: 'If D completes a task for $100:',
    refEarn: 'Earns'
  },
  zh: {
    home: '首页',
    earn: '赚钱',
    tasks: '任务',
    profile: '个人中心',
    referral: '邀请好友',
    login: '登录',
    register: '注册',
    merchantLogin: '商家后台登录',
    phone: '手机号码',
    password: '登录密码',
    verifyCode: '短信验证码',
    getCode: '获取验证码',
    appName: '博彩宝',
    balance: '可提现余额',
    withdraw: '申请提现',
    bindCard: '绑定银行卡',
    totalEarnings: '累计收益',
    submitProof: '提交凭证',
    uploadScreenshot: '上传充值截图',
    audit: '审核管理',
    approve: '通过',
    reject: '拒绝',
    status: { ongoing: '进行中', reviewing: '审核中', completed: '已完成', rejected: '已拒绝' },
    adminTabs: { users: '用户管理', tasks: '任务发布', activities: '活动管理', audit: '任务审核' },
    sort: '排序',
    sortNew: '最新',
    sortReward: '高奖励',
    sortDeposit: '低门槛',
    startTask: '立即参与',
    steps: '任务步骤',
    rules: '活动规则',
    uploadPlatform: '发布任务',
    hot: '热门',
    reward: '奖励',
    remaining: '剩余',
    activityTitle: '热门活动',
    play: '去看看',
    wait: '请稍候',
    sent: '已发送',
    submit: '提交',
    myTasksTitle: '我的任务',
    noTasks: '暂无任务',
    scanQr: '扫码加入',
    shareCode: '我的邀请码',
    shareLink: '分享链接',
    copy: '复制',
    copied: '已复制',
    messages: '站内信',
    notifications: '消息通知',
    telegram: '官方频道',
    referralRules: '三级分销 无限返利',
    referralDesc: '邀请好友完成任务，您将永久获得下级任务奖励的提成。',
    level1: '一级好友 (直推)',
    level2: '二级好友',
    level3: '三级好友',
    bankName: '银行名称',
    accHolder: '持卡人姓名',
    accNumber: '银行卡号',
    save: '保存',
    cancel: '取消',
    activityName: '活动标题',
    targetCountry: '目标国家',
    uploadImage: '上传活动图',
    addActivity: '发布新活动',
    activityContent: '活动详情',
    createTask: '发布新任务',
    taskName: '任务名称',
    taskDesc: '简单描述',
    taskRules: '详细规则',
    taskReward: '奖励金额',
    example: '举例说明',
    refExampleA: '您 (A)',
    refExampleB: '好友 (B)',
    refExampleC: '好友 (C)',
    refExampleD: '好友 (D)',
    refCalc: '如果 D 完成了一个 100元的任务:',
    refEarn: '获得'
  },
  id: {
    home: 'Beranda',
    earn: 'Hasilkan',
    tasks: 'Tugas',
    profile: 'Saya',
    referral: 'Undang',
    login: 'Masuk',
    register: 'Daftar',
    merchantLogin: 'Portal Pedagang',
    phone: 'Nomor HP',
    password: 'Kata Sandi',
    verifyCode: 'Kode SMS',
    getCode: 'Dapatkan Kode',
    appName: 'PusatCuan',
    balance: 'Saldo',
    withdraw: 'Tarik',
    bindCard: 'Ikat Kartu',
    totalEarnings: 'Total Pendapatan',
    submitProof: 'Kirim Bukti',
    uploadScreenshot: 'Unggah Tangkapan Layar',
    audit: 'Audit',
    approve: 'Setuju',
    reject: 'Tolak',
    status: { ongoing: 'Berjalan', reviewing: 'Ditinjau', completed: 'Selesai', rejected: 'Ditolak' },
    adminTabs: { users: 'Pengguna', tasks: 'Tugas', activities: 'Aktivitas', audit: 'Audit Tugas' },
    sort: 'Urutkan',
    sortNew: 'Terbaru',
    sortReward: 'Hadiah',
    sortDeposit: 'Depo Rendah',
    startTask: 'Gabung Sekarang',
    steps: 'Langkah',
    rules: 'Aturan',
    uploadPlatform: 'Unggah',
    hot: 'PANAS',
    reward: 'Hadiah',
    remaining: 'Sisa',
    activityTitle: 'Acara',
    play: 'Main',
    wait: 'Tunggu',
    sent: 'Terkirim',
    submit: 'Kirim',
    myTasksTitle: 'Tugas Saya',
    noTasks: 'Tidak ada tugas',
    scanQr: 'Pindai QR',
    shareCode: 'Kode Referensi',
    shareLink: 'Bagikan Tautan',
    copy: 'Salin',
    copied: 'Disalin!',
    messages: 'Pesan',
    notifications: 'Notifikasi',
    telegram: 'Saluran',
    referralRules: 'Undang & Hasilkan Selamanya',
    referralDesc: 'Undang teman untuk bergabung dan dapatkan komisi dari setiap tugas yang mereka selesaikan.',
    level1: 'Level 1 (Langsung)',
    level2: 'Level 2',
    level3: 'Level 3',
    bankName: 'Nama Bank',
    accHolder: 'Nama Pemilik',
    accNumber: 'Nomor Rekening',
    save: 'Simpan',
    cancel: 'Batal',
    activityName: 'Judul Acara',
    targetCountry: 'Negara Tujuan',
    uploadImage: 'Unggah Gambar',
    addActivity: 'Tambah Acara',
    activityContent: 'Konten Acara',
    createTask: 'Buat Tugas Baru',
    taskName: 'Nama Tugas',
    taskDesc: 'Deskripsi',
    taskRules: 'Aturan',
    taskReward: 'Jumlah Hadiah',
    example: 'Contoh',
    refExampleA: 'Anda (A)',
    refExampleB: 'Teman (B)',
    refExampleC: 'Teman (C)',
    refExampleD: 'Teman (D)',
    refCalc: 'Jika D menyelesaikan tugas Rp 100.000:',
    refEarn: 'Dapat'
  },
  // Brief fallbacks for others
  th: { home: 'หน้าแรก', earn: 'รายได้', tasks: 'ภารกิจ', profile: 'ฉัน', referral: 'ชวนเพื่อน', login: 'เข้าสู่ระบบ', register: 'ลงทะเบียน', merchantLogin: 'ผู้ค้า', phone: 'เบอร์โทร', password: 'รหัสผ่าน', verifyCode: 'รหัส SMS', getCode: 'รับรหัส', appName: 'BetBounty', balance: 'ยอดเงิน', withdraw: 'ถอนเงิน', bindCard: 'ผูกบัญชี', totalEarnings: 'รายได้รวม', submitProof: 'ส่งหลักฐาน', uploadScreenshot: 'อัปโหลด', audit: 'ตรวจสอบ', approve: 'อนุมัติ', reject: 'ปฏิเสธ', status: { ongoing: 'กำลังทำ', reviewing: 'รอตรวจ', completed: 'เสร็จ', rejected: 'ไม่ผ่าน' }, adminTabs: { users: 'ผู้ใช้', tasks: 'งาน', activities: 'กิจกรรม', audit: 'ตรวจงาน' }, sort: 'เรียง', sortNew: 'ใหม่', sortReward: 'รางวัล', sortDeposit: 'ฝาก', startTask: 'เข้าร่วมเลย', steps: 'ขั้นตอน', rules: 'กฎ', uploadPlatform: 'สร้างงาน', hot: 'ฮอต', reward: 'รางวัล', remaining: 'เหลือ', activityTitle: 'กิจกรรม', play: 'เล่น', wait: 'รอ', sent: 'ส่งแล้ว', submit: 'ยืนยัน', myTasksTitle: 'งานของฉัน', noTasks: 'ไม่มีงาน', scanQr: 'สแกน QR', shareCode: 'รหัสแนะนำ', shareLink: 'แชร์ลิงก์', copy: 'คัดลอก', copied: 'คัดลอกแล้ว', messages: 'ข้อความ', notifications: 'การแจ้งเตือน', telegram: 'ช่องทาง', referralRules: 'เชิญเพื่อน & รับรายได้', referralDesc: 'รับค่าคอมมิชชั่น 3 ระดับ', level1: 'ระดับ 1 (20%)', level2: 'ระดับ 2 (10%)', level3: 'ระดับ 3 (5%)', bankName: 'ชื่อธนาคาร', accHolder: 'ชื่อบัญชี', accNumber: 'เลขบัญชี', save: 'บันทึก', cancel: 'ยกเลิก', activityName: 'ชื่อกิจกรรม', targetCountry: 'ประเทศ', uploadImage: 'อัปโหลดรูป', addActivity: 'เพิ่มกิจกรรม', activityContent: 'เนื้อหากิจกรรม', createTask: 'สร้างงานใหม่', taskName: 'ชื่องาน', taskDesc: 'คำอธิบาย', taskRules: 'กฎ', taskReward: 'รางวัล', example: 'ตัวอย่าง', refExampleA: 'คุณ (A)', refExampleB: 'เพื่อน (B)', refExampleC: 'เพื่อน (C)', refExampleD: 'เพื่อน (D)', refCalc: 'หาก D ทำงานสำเร็จ 100 บาท:', refEarn: 'ได้รับ' },
  vi: { home: 'Trang chủ', earn: 'Kiếm', tasks: 'Nhiệm vụ', profile: 'Tôi', referral: 'Mời', login: 'Đăng nhập', register: 'Đăng ký', merchantLogin: 'Người bán', phone: 'SĐT', password: 'Mật khẩu', verifyCode: 'Mã SMS', getCode: 'Lấy mã', appName: 'BetBounty', balance: 'Số dư', withdraw: 'Rút tiền', bindCard: 'Thẻ', totalEarnings: 'Tổng thu nhập', submitProof: 'Nộp bằng chứng', uploadScreenshot: 'Tải ảnh', audit: 'Duyệt', approve: 'Duyệt', reject: 'Từ chối', status: { ongoing: 'Đang làm', reviewing: 'Đang duyệt', completed: 'Xong', rejected: 'Hủy' }, adminTabs: { users: 'Người dùng', tasks: 'NV', activities: 'HĐ', audit: 'Duyệt NV' }, sort: 'Xếp', sortNew: 'Mới', sortReward: 'Thưởng', sortDeposit: 'Nạp', startTask: 'Tham gia ngay', steps: 'Bước', rules: 'Luật', uploadPlatform: 'Đăng NV', hot: 'HOT', reward: 'Thưởng', remaining: 'Còn', activityTitle: 'Sự kiện', play: 'Đi', wait: 'Chờ', sent: 'Đã gửi', submit: 'Gửi', myTasksTitle: 'NV của tôi', noTasks: 'Không có NV', scanQr: 'Quét QR', shareCode: 'Mã mời', shareLink: 'Chia sẻ', copy: 'Sao chép', copied: 'Đã sao chép', messages: 'Tin nhắn', notifications: 'Thông báo', telegram: 'Kênh', referralRules: 'Mời bạn & Kiếm tiền', referralDesc: 'Nhận hoa hồng 3 cấp', level1: 'Cấp 1 (20%)', level2: 'Cấp 2 (10%)', level3: 'Cấp 3 (5%)', bankName: 'Tên ngân hàng', accHolder: 'Chủ tài khoản', accNumber: 'Số tài khoản', save: 'Lưu', cancel: 'Hủy', activityName: 'Tên hoạt động', targetCountry: 'Quốc gia', uploadImage: 'Tải ảnh lên', addActivity: 'Thêm hoạt động', activityContent: 'Nội dung', createTask: 'Tạo nhiệm vụ', taskName: 'Tên nhiệm vụ', taskDesc: 'Mô tả', taskRules: 'Luật', taskReward: 'Phần thưởng', example: 'Ví dụ', refExampleA: 'Bạn (A)', refExampleB: 'Bạn (B)', refExampleC: 'Bạn (C)', refExampleD: 'Bạn (D)', refCalc: 'Nếu D hoàn thành 100k:', refEarn: 'Nhận' },
  ms: { home: 'Rumah', earn: 'Dapat', tasks: 'Tugas', profile: 'Saya', referral: 'Jemput', login: 'Log Masuk', register: 'Daftar', merchantLogin: 'Peniaga', phone: 'No Tel', password: 'Kata Laluan', verifyCode: 'Kod SMS', getCode: 'Dapat Kod', appName: 'BetBounty', balance: 'Baki', withdraw: 'Keluarkan', bindCard: 'Ikat', totalEarnings: 'Jumlah', submitProof: 'Hantar Bukti', uploadScreenshot: 'Muat Naik', audit: 'Audit', approve: 'Lulus', reject: 'Tolak', status: { ongoing: 'Sedang', reviewing: 'Semakan', completed: 'Selesai', rejected: 'Gagal' }, adminTabs: { users: 'Pengguna', tasks: 'Tugas', activities: 'Aktiviti', audit: 'Audit' }, sort: 'Susun', sortNew: 'Baru', sortReward: 'Ganjaran', sortDeposit: 'Depo', startTask: 'Sertai Sekarang', steps: 'Langkah', rules: 'Peraturan', uploadPlatform: 'Muat Naik', hot: 'PANAS', reward: 'Ganjaran', remaining: 'Baki', activityTitle: 'Acara', play: 'Main', wait: 'Tunggu', sent: 'Dihantar', submit: 'Hantar', myTasksTitle: 'Tugas Saya', noTasks: 'Tiada tugas', scanQr: 'Imbas QR', shareCode: 'Kod Jemputan', shareLink: 'Kongsi', copy: 'Salin', copied: 'Disalin', messages: 'Mesej', notifications: 'Notifikasi', telegram: 'Saluran', referralRules: 'Jemput & Jana', referralDesc: 'Komisen 3 Tahap', level1: 'Tahap 1 (20%)', level2: 'Tahap 2 (10%)', level3: 'Tahap 3 (5%)', bankName: 'Nama Bank', accHolder: 'Pemegang Akaun', accNumber: 'Nomor Akaun', save: 'Simpan', cancel: 'Batal', activityName: 'Nama Aktiviti', targetCountry: 'Negara', uploadImage: 'Muat Naik', addActivity: 'Tambah Aktiviti', activityContent: 'Kandungan', createTask: 'Buat Tugas', taskName: 'Nama', taskDesc: 'Penerangan', taskRules: 'Peraturan', taskReward: 'Ganjaran', example: 'Contoh', refExampleA: 'Anda (A)', refExampleB: 'Rakan (B)', refExampleC: 'Rakan (C)', refExampleD: 'Rakan (D)', refCalc: 'Jika D selesai RM100:', refEarn: 'Dapat' },
  tl: { home: 'Bahay', earn: 'Kita', tasks: 'Gawain', profile: 'Ako', referral: 'Imbita', login: 'Login', register: 'Register', merchantLogin: 'Merchant', phone: 'Telepono', password: 'Password', verifyCode: 'SMS Code', getCode: 'Kumuha', appName: 'BetBounty', balance: 'Balanse', withdraw: 'Withdraw', bindCard: 'Card', totalEarnings: 'Kabuuang Kita', submitProof: 'Ipasa', uploadScreenshot: 'Upload', audit: 'Audit', approve: 'Approve', reject: 'Reject', status: { ongoing: 'Ginagawa', reviewing: 'Review', completed: 'Tapos', rejected: 'Reject' }, adminTabs: { users: 'Users', tasks: 'Tasks', activities: 'Activities', audit: 'Audit' }, sort: 'Ayusin', sortNew: 'Bago', sortReward: 'Premyo', sortDeposit: 'Depo', startTask: 'Sumali Ngayon', steps: 'Hakbang', rules: 'Tuntunin', uploadPlatform: 'Upload', hot: 'INIT', reward: 'Gantimpala', remaining: 'Natitira', activityTitle: 'Event', play: 'Laro', wait: 'Sandali', sent: 'Naipadala', submit: 'Ipasa', myTasksTitle: 'Gawain Ko', noTasks: 'Walang gawain', scanQr: 'Scan QR', shareCode: 'Referral Code', shareLink: 'Share', copy: 'Copy', copied: 'Copied', messages: 'Messages', notifications: 'Notifications', telegram: 'Channel', referralRules: 'Invite & Earn', referralDesc: '3-Level Commission', level1: 'Level 1 (20%)', level2: 'Level 2 (10%)', level3: 'Level 3 (5%)', bankName: 'Bank Name', accHolder: 'Account Name', accNumber: 'Account Number', save: 'Save', cancel: 'Cancel', activityName: 'Activity Name', targetCountry: 'Country', uploadImage: 'Upload Image', addActivity: 'Add Activity', activityContent: 'Content', createTask: 'Create Task', taskName: 'Name', taskDesc: 'Description', taskRules: 'Rules', taskReward: 'Reward', example: 'Example', refExampleA: 'You (A)', refExampleB: 'Friend (B)', refExampleC: 'Friend (C)', refExampleD: 'Friend (D)', refCalc: 'If D earns 100:', refEarn: 'Earns' },
};

export const MOCK_PLATFORMS: Platform[] = [
  {
    id: '1',
    name: 'RoyalWin Indonesia',
    logoUrl: 'https://picsum.photos/100/100?random=1',
    description: 'Best slots and live casino in Indonesia. High Win Rate!',
    downloadLink: 'https://example.com/download/royalwin',
    firstDepositAmount: 50000,
    rewardAmount: 15000,
    launchDate: '2023-10-01',
    isHot: true,
    remainingQty: 45,
    totalQty: 100,
    steps: ['Click "Start Task" to download APK', 'Register with phone number', 'Deposit 50k IDR', 'Upload screenshot of deposit'],
    rules: 'New users only. Deposit must be made within 24 hours of registration.',
    status: 'online',
    type: 'deposit',
    targetCountries: ['id'] // Only for Indonesia
  },
  {
    id: '2',
    name: 'ThaiLucky Lotto',
    logoUrl: 'https://picsum.photos/100/100?random=2',
    description: 'Thai number 1 lottery app.',
    downloadLink: 'https://example.com/download/thailucky',
    firstDepositAmount: 200, // THB
    rewardAmount: 50, // THB
    launchDate: '2023-11-15',
    remainingQty: 12,
    totalQty: 50,
    steps: ['Download App', 'Register', 'Deposit 200 THB'],
    rules: 'Screenshot must show the transaction ID.',
    status: 'online',
    type: 'deposit',
    targetCountries: ['th'] // Only for Thailand
  },
  {
    id: '3',
    name: 'Global Bet',
    logoUrl: 'https://picsum.photos/100/100?random=3',
    description: 'Crypto betting for everyone.',
    downloadLink: 'https://example.com/download/global',
    firstDepositAmount: 10, // USD
    rewardAmount: 5, // USD
    launchDate: '2023-12-01',
    isHot: true,
    remainingQty: 88,
    totalQty: 200,
    steps: ['Visit Link', 'Sign Up', 'Buy 1 Ticket'],
    rules: 'Any ticket purchase qualifies.',
    status: 'online',
    type: 'register',
    targetCountries: 'all' // All countries
  },
  {
    id: '4',
    name: 'VinaWin 88',
    logoUrl: 'https://picsum.photos/100/100?random=4',
    description: 'Game bài đổi thưởng uy tín.',
    downloadLink: 'https://example.com/download/vinawin',
    firstDepositAmount: 100000, // VND
    rewardAmount: 30000, // VND
    launchDate: '2023-12-10',
    remainingQty: 100,
    totalQty: 500,
    steps: ['Tải app', 'Đăng ký SĐT', 'Nạp đầu 100k'],
    rules: 'Chỉ dành cho người chơi mới.',
    status: 'online',
    type: 'deposit',
    targetCountries: ['vi']
  },
   {
    id: '5',
    name: 'China Gold Casino',
    logoUrl: 'https://picsum.photos/100/100?random=5',
    description: '澳门线上博彩.',
    downloadLink: 'https://example.com/download/china',
    firstDepositAmount: 100, // RMB
    rewardAmount: 28, // RMB
    launchDate: '2023-12-12',
    remainingQty: 50,
    totalQty: 100,
    steps: ['下载APP', '注册', '首充'],
    rules: '仅限新用户',
    status: 'online',
    type: 'deposit',
    targetCountries: ['zh']
  }
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    title: 'Indo Special Bonus',
    imageUrl: 'https://picsum.photos/800/400?random=10',
    content: 'Deposit 50k to get 20k extra bonus! Limited time offer for new Indonesian users. \n\n1. Register via our link.\n2. Deposit 50,000 IDR.\n3. Get automatic cashback to your wallet.',
    link: '/task/1',
    active: true,
    targetCountries: ['id']
  },
  {
    id: 'a2',
    title: 'Songkran Festival',
    imageUrl: 'https://picsum.photos/800/400?random=11',
    content: 'Celebrate Songkran with double rewards on all Thai lottery tasks. Happy New Year!',
    link: '/task/2',
    active: true,
    targetCountries: ['th']
  },
  {
    id: 'a3',
    title: 'VIP Invite Global',
    imageUrl: 'https://picsum.photos/800/400?random=12',
    content: 'Invite 10 friends and become a VIP agent. Earn 25% commission on level 1 referrals permanently.',
    link: '/referral',
    active: true,
    targetCountries: 'all'
  }
];